name: Deploy to Windows Server

on:
  push:
    branches:
      stg_env:
        description: Environment
        required: true
        type: choice        
        options: 
        - stg                  
      branch:
        description: Branch
        required: true
        type: string  
        default: 'main'        

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Specify a self-hosted runner on Windows Server
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build code
        run: |
          echo "TESTING" 
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: path/to/artifacts
      # - name: Deploy to Windows Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /path/to/deployment/directory
      #       mkdir -p ./my-app
      #       scp -r ${{ runner.temp }}/my-artifact/* ./my-app
      #       # Additional deployment commands (e.g., start services)
